### ISSUE TITLE
app.OpenSharedParameterFile() returns null

### ISSUE THREAD

**Issue by AnweshGangula** [jeremytammik/TraverseAllSystems#3]
I was trying to use this repo as a project in one of my existing Visual Studio solutions and made some change so that the json is returned as an output from the `Command` class. 
but after building this project, I'm receiving an error that `Object reference is not set to an instance of an object`

Debugging it shows that the [following line][1] in `SharedParameterMgr.cs` class returns null value

```c#
DefinitionFile f = app.OpenSharedParameterFile(); // returns f = null
```

And `app.SharedParametersFilename` is not null. It returns a file in a temp folder. But when I look for it, I can't find it.

![SharedParameter null](https://user-images.githubusercontent.com/22996896/182530846-80de3c0b-3bce-432f-a379-778e94fe46e5.png)

> Note: It was working fine till yesterday - when I was using this project by itself . And after adding this in another project, I'm receiving the same error even in this solution(2017.0.0.8) which I'm building as its currently available.

[1]: https://github.com/jeremytammik/TraverseAllSystems/blob/master/TraverseAllSystems/SharedParameterMgr.cs#L102

**Comment by jeremytammik** [comment]
Great! Thank you very much!
