### ISSUE TITLE
Elements with Curve ConnectorType are being ignored 

### ISSUE THREAD

**Issue by AnweshGangula** [jeremytammik/TraverseAllSystems#5]
I was using the code in one of my projects and noticed that when there is a "Duct Riser" which runs across multiple floors, the elements that connect to this duct have `conn.ConnectorType == ConnectorType.Curve`(_API Docs link: [ConnectorType][1]_). These elements were being ignored in the condition during `GetConnectedConnector` at [line 699 in TraversalTree.cs][2]. So I added a condition to include these elements as well and got it to work as expected in this case.

Wondering if this could cause any unexpected behavior.

Below is the change:

```csharp
if ((conn.ConnectorType != ConnectorType.End &&
    conn.ConnectorType != ConnectorType.Curve) ||
    conn.Owner.Id.IntegerValue.Equals(connector.Owner.Id.IntegerValue))
```

Also note that out of 2032 elements in all of my MEP systems, I found only 3 elements which have `conn.ConnectorType = ConnectorType.Curve`. And one of the possible reasons for this that we are assuming is that the connected ducts are not aligned to the center of these ducts.

Below is a sample screenshot:
![Revit Screenshot highlighting one of the duct elements which has conn.ConnectorType = ConnectorType.Curve](https://user-images.githubusercontent.com/22996896/185426684-b76d9edd-eedc-4d2b-997d-185f2433cec0.png)

[1]: https://www.revitapidocs.com/2021.1/769d8156-55b0-bda8-9e8f-f81fce49f1af.htm
[2]: https://github.com/jeremytammik/TraverseAllSystems/blob/a378fa9c3ab2da2f8f9166c5dcd4542c7c313636/TraverseAllSystems/TraversalTree.cs#L699

**Comment by jeremytammik** [comment]
Your enhancement sounds very valid to me. I hope you are right. Thank you very much for the explanation and fix!
